### ISSUE TITLE
Enforce function arguments with exception or type-hint

### ISSUE THREAD

**Issue by gmazzap** [tomphp/php-transform#5]
Currently most of the functions just assumes proper arguments are passed to functions, and type hint is never used.

For example, `chain()` just assumes to receive a variadic number of callables. **No** type-hint is used.
If non-callable arguments are passed, the function exit with a ugly fatal error.
In this case is possible to enforce the type using type hint.

In other cases, that is not possible, because with PHP < 7 support, is not possible to use scalar type hint.

For those cases, I think would be fine to throws explicative exceptions when bad arguments are given.

**Comment by tomphp** [comment]
Sounds good! Thanks.

**Comment by tomphp** [comment]
Addressed in #12
