### ISSUE TITLE
Consider deprecating `argumentTo()`: it does nothing

### ISSUE THREAD

**Issue by gmazzap** [tomphp/php-transform#7]
The function `argumentTo()` does pratically nothing.

It looks like this:

``` php
function argumentTo($callable)
{
    return function ($value) use ($callable) {
        return $callable($value);
    };
}
```

but it could be:

``` php
function argumentTo($callable)
{
    return $callable;
}
```

Without changes. Actuall, the only real change is that, in current form, it forces the passed callable to accept just 1 argument. If that was the wanted behaviour, then it is misnamed, but I actually can't imagibe the benefit of this function.

Any function that would accet the transformer callback could work justdirectly accepting the callback.

E.g.

``` php
$callable = [$class, 'methodName'];
$t = T\argumentTo($callable);

$result = $t($argument);
```

is exactly equal to:

``` php
$callable = [$class, 'methodName'];

$result = $callable($argument);
```

but with some chars more...

**Comment by tomphp** [comment]
You raise a very valid point about this function in its current state. However, I was thinking to extend `argumentTo` to be able to take additional arguments - maybe something like this:

``` php
T\argumentTo('substr'. [T\argument(), 0, 5])
```

to cover this use case:

``` php
function ($value) {
    return substr($value, 0, 5);
}
```

Any thoughts?

**Comment by gmazzap** [comment]
If changed in like that it could be actually useful, but probably misnamed... the name `argumentTo()` gives me no hint on what the functions does in that case.

But: have you idea how to implement `T\argument()`? I have one, but not very elegant. (see https://3v4l.org/TAPPF)

**Comment by tomphp** [comment]
Your implementation is very similar to the one I implemented (https://github.com/tomphp/php-transform/blob/master/src/transform.php#L143).

I'm going to close this ticket but feel let me know if you can think of improvements (I like your random idea - it some strange way it's more elegant that what I did).

**Comment by gmazzap** [comment]
I saw your implementation after having wrote the comment. However, I think that  for that purpose an unpredictable random string is more defensive code, because an hardcoded string is easily reproducible just looking at (open source) code.

It's not really "elegant" but due to userland PHP limits I can't find a more elegant solution. Maybe [a constant](https://3v4l.org/e4B8h)?

**Comment by tomphp** [comment]
The random string is definitely a good idea - will add it soon.
